# 서버 설정
server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8

logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure:
                        security: INFO
                security: DEBUG
# 뷰리졸버 설정
spring:
    mvc:
        view:
            prefix: /WEB-INF/jblog/
            suffix: .jsp
    datasource:
        password: 1234
        url: jdbc:mysql://127.0.0.1:3306/spring_test?serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true

# 카카오 비밀번호
kakao:
    default:
        password: kakao123